#!/bin/sh
# Generate packages/debian.txt, packages/fedora.txt and packages/Brewfile from
# packages/manifest.tsv, or (--check) verify that the generated files match.
#
# The point is that a tool is declared once. Three hand-maintained lists drift
# within a month: someone adds ripgrep to the Debian list, forgets Fedora, and
# the difference only surfaces on a machine nobody has bootstrapped yet.
set -eu

root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd -P)
manifest="$root/packages/manifest.tsv"

mode=regenerate
if [ "${1:-}" = --check ]; then
    mode=check
fi

# $1 = manifest column, $2 = output format (list|brewfile)
emit() {
    printf '# Generated by scripts/gen-packages.sh from packages/manifest.tsv.\n'
    printf '# Edit the manifest, not this file.\n'
    awk -F'\t' -v column="$1" -v format="$2" '
        /^#/ || /^[[:space:]]*$/ { next }
        $column == "-" { next }
        format == "brewfile" { printf "brew \"%s\"\n", $column; next }
        { print $column }
    ' "$manifest" | LC_ALL=C sort
}

# $1 = path relative to the repository root, $2 = column, $3 = format
generate() {
    if [ "$mode" = regenerate ]; then
        emit "$2" "$3" >"$root/$1"
        printf 'wrote %s\n' "$1"
        return 0
    fi
    generate_diff=$(mktemp)
    if emit "$2" "$3" | diff -u "$root/$1" - >"$generate_diff"; then
        rm -f "$generate_diff"
        printf 'ok    %s\n' "$1"
        return 0
    fi
    printf '%s is out of date; run scripts/gen-packages.sh\n' "$1" >&2
    cat "$generate_diff" >&2
    rm -f "$generate_diff"
    return 1
}

status=0
generate packages/debian.txt 2 list || status=1
generate packages/fedora.txt 3 list || status=1
generate packages/Brewfile 4 brewfile || status=1
exit "$status"
